# Form implementation generated from reading ui file 'skin_cancer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 588)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(210, 10, 301, 31))
        self.lblTitle.setObjectName("lblTitle")
        self.lblImage = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblImage.setGeometry(QtCore.QRect(160, 50, 401, 241))
        self.lblImage.setAutoFillBackground(False)
        self.lblImage.setStyleSheet("border-radius: 10px;\n"
"border: 2px solid gray;\n"
"box-shadow: 2px 2px 5px #888888;\n"
"background-color: lightgray;\n"
"\n"
"")
        self.lblImage.setText("")
        self.lblImage.setObjectName("lblImage")
        self.btnUpload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnUpload.setGeometry(QtCore.QRect(90, 330, 121, 31))
        self.btnUpload.setObjectName("btnUpload")
        self.btnClassify = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClassify.setGeometry(QtCore.QRect(300, 330, 121, 31))
        self.btnClassify.setObjectName("btnClassify")
        self.txtResult = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(270, 430, 381, 41))
        self.txtResult.setObjectName("txtResult")
        self.btnTrain = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTrain.setGeometry(QtCore.QRect(520, 330, 101, 31))
        self.btnTrain.setObjectName("btnTrain")
        self.lblHeadingResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblHeadingResult.setGeometry(QtCore.QRect(70, 440, 171, 16))
        self.lblHeadingResult.setObjectName("lblHeadingResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">SKIN CANCER DETECTION</span></p></body></html>"))
        self.btnUpload.setText(_translate("MainWindow", "upload image"))
        self.btnClassify.setText(_translate("MainWindow", "classify"))
        self.btnTrain.setText(_translate("MainWindow", "training"))
        self.lblHeadingResult.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">RECOGNISED CLASS:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

import sys
from PyQt6 import QtWidgets, QtGui
from PyQt6.QtWidgets import QFileDialog, QMessageBox
from keras.models import load_model
import numpy as np
from PIL import Image


class MainApp(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Connect buttons to functions
        self.ui.btnUpload.clicked.connect(self.upload_image)
        self.ui.btnClassify.clicked.connect(self.classify_image)

        # Initialize variables
        self.uploaded_file = None
        self.model = None

        # Load the trained model
        self.load_model()

    def load_model(self):
        try:
            self.model = load_model("C:/Users/Dell/skin_cancer_mobilenetv2.h5")
            QMessageBox.information(self, "Success", "Model loaded successfully!")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Error loading model: {e}")

    def upload_image(self):
        # Open a file dialog to select image
        file_path, _ = QFileDialog.getOpenFileName(self, "Upload Image", "", "Images (*.png *.jpg *.jpeg)")
        if file_path:
            self.uploaded_file = file_path
            pixmap = QtGui.QPixmap(file_path)
            self.ui.lblImage.setPixmap(pixmap.scaled(self.ui.lblImage.size(), QtCore.Qt.AspectRatioMode.KeepAspectRatio))
        else:
            QMessageBox.warning(self, "Warning", "No image selected!")

    def preprocess_image(self, file_path):
        # Preprocess the image for model input
        img = Image.open(file_path).convert("RGB")
        img = img.resize((32, 32))  # Match the model input size
        img_array = np.array(img) / 255.0  # Normalize pixel values
        img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
        return img_array

    def classify_image(self):
        if not self.uploaded_file:
            QMessageBox.warning(self, "Error", "Please upload an image first!")
            return

        try:
            # Preprocess image and classify
            input_data = self.preprocess_image(self.uploaded_file)
            prediction = self.model.predict(input_data)

            # Map prediction to class
            classes = ['nv', 'mel', 'bkl', 'bcc', 'akiec', 'vas', 'df']
            predicted_class = classes[np.argmax(prediction)]
            self.ui.txtResult.setText(f"Recognized Class: {predicted_class}")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Error in classification: {e}")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    main_window = MainApp()
    main_window.show()
    sys.exit(app.exec())
    

    
